[phases.setup]
nixpkgs = "python311"
[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]
[start]
 cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT summarize:app"
[variables]
PYTHONUNBUFFERED = "1"
