# Specify the Python runtime using Nixpacks
[phases.setup]
nixpkgs = ["python39","pip"]  # Use Python 3.9 (or update as needed)

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:8080 summarize:app"

# Environment variables
[env]
PORT = "8080"
FLASK_ENV = "productio"
PYTHONUNBUFFERED = "1"
NLTK_DATA = "/app/nltk_data"  # Use existing nltk_data folder

