[phases.setup]
nixpkgs = "python311"

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python summarize.py"

[variables]
PYTHONUNBUFFERED = "1"
